# Generated by Django 4.0.1 on 2022-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('done_for_today', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.TextField()),
            ],
        ),
    ]
