# Generated by Django 4.0.1 on 2022-03-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_for_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('difficulty', models.BooleanField(default=False)),
                ('reason_for_goal', models.CharField(max_length=100)),
            ],
        ),
    ]
