# Generated by Django 4.0.1 on 2022-03-16 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_goal_for_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_for_month',
            name='goal',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='comment',
            field=models.TextField(),
        ),
    ]
