# Generated by Django 4.0.1 on 2022-03-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateField(),
        ),
    ]
